"""make password_hash nullable

Revision ID: 7d2920a07a59
Revises: 9e13212a1495
Create Date: 2025-12-24 00:10:28.734768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7d2920a07a59'
down_revision: Union[str, Sequence[str], None] = '9e13212a1495'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_account', 'password_hash',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=True)
    op.drop_index(op.f('uniq_user_account_phone_not_deleted'), table_name='user_account')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uniq_user_account_phone_not_deleted'), 'user_account', ['phone', 'is_deleted'], unique=True)
    op.alter_column('user_account', 'password_hash',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=False)
    # ### end Alembic commands ###
