"""create user_account table

Revision ID: 9e13212a1495
Revises: 7906d6cae979
Create Date: 2025-12-23 10:10:02.203582

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e13212a1495'
down_revision: Union[str, Sequence[str], None] = '7906d6cae979'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('id_card_no', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('major', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('student_no', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('is_verified_campus', sa.Integer(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(
        "uniq_user_account_phone_not_deleted",
        "user_account",
        ["phone", "is_deleted"]
    )
    op.create_index(op.f('ix_user_account_is_deleted'), 'user_account', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uniq_user_account_phone_not_deleted",
        "user_account",
        type_="unique"
    )
    op.drop_table('user_account')
    # ### end Alembic commands ###
